### PR TITLE
edit def.groups

### PR DESCRIPTION
**Pull request by Napiophelios**
replace def.groups.not_in_creative_inventory=1
with def.groups.not_in_craft_guide=1

### CODE REVIEW

**Comment by t4im** [comment]
`not_in_creative_inventory` is the conventional group that is used by all mods in minetest and should be considered by all inventory and crafting guide mods.

Replacing this with a new group would lead to items being listed, that are supposed to be hidden from crafting guides.

**Comment by Napiophelios** [comment]
Oh, I didn't make it up myself.
its an old setting that just seems to have been forgotten.
Its used in the older craft guides and a couple of mods I still use.

**Comment by t4im** [comment]
Interesting. And there even seem to be a few mods out there still using `not_in_craft_guide`.

I don't oppose adding support for it here, but we can't ignore `not_in_creative_inventory` either.

It is also being checked by both [craft_guide](https://github.com/cornernote/minetest-craft_guide/blob/master/craft_guide/api_craft_guide.lua#L1802) and [unified inventory](https://github.com/minetest-technic/unified_inventory/blob/master/api.lua#L13), with full exclusions from the craft guides and we can't change that convention from here alone.

Circsaw/stairsplus elements for example have recipes, that are supposed to be hidden from crafting guides by means of that group.

I agree with you, that the current convention needs a do-over. But until then, we'll have to support the current one, too.

**Comment by kilbith** [comment]
I don't think this group is relevant anymore. Thanks for your contribution anyway.

**Pull request closed without merging**
