### PR TITLE
Remove formspec background

### PR DESCRIPTION
**Pull request by pauloue**
This doesn't change the background in MTG (except a slight different in the border). For other games it will depend on what the formspec prepend is set as.

### CODE REVIEW

**Comment by kilbith** [comment]
Oops, didn't notice that. Fixed: https://github.com/minetest-mods/craftguide/commit/1def071029f3eacf09e93721dceb822afe0d472e

**Comment by pauloue** [comment]
That breaks formspec theming. Why shouldn't games be allowed to customize the background for consistency with other formspecs? At least move the background into the not sfinv block so there's no inconsistency when switching tabs.

**Comment by kilbith** [comment]
The `sfinv` tab keeps the `minetest_game` default background. I don't think there is a need for theming.

**Comment by pauloue** [comment]
Image buttons could be used (like MineClone2). But if everyone does use the same dark grey background as MTG, why does craftguide need to override it with it's own almost identical background?

**Comment by kilbith** [comment]
> Image buttons could be used

Dark-ish as well.

**Comment by pauloue** [comment]
> Dark-ish as well.

Not if you use a light texture ?

Also `set_formspec_prepend` sets more than just the background. craftguide now has inconsistent tooltips.

**Comment by kilbith** [comment]
I deleted my comment for a reason, pauloue. Also there is no way to convince me otherwise, sorry. If the game creators want a different theme, they can do it in their forks.

**Comment by pauloue** [comment]
Sorry, didn't see that.

**Pull request closed without merging**
