### PR TITLE
Fix tooltip display

### PR DESCRIPTION
**Pull request by louisroyer**
Tooltip was displaying "Unknown item" on empty slots when using a
replacement in craft.

You can test this by installing [basic_materials](https://gitlab.com/VanessaE/basic_materials/-/blob/master/misc.lua) and looking at the craft for `basic_materials:terracotta_base`.

Note: the `R` symbol is printed on each slot and this is weird (I expected it to be only printed on the bucket) but I don't know how to fix this.

### CODE REVIEW

**Comment by kilbith** [comment]
Tooltips don't work like that but I'll fix it later.

**Comment by louisroyer** [comment]
Ok.
I have another bug related to tooltip when replacement is set with more than 1 item:
2020-07-12-202929_1366x768_scrot
Here, I have:
```lua
minetest.register_craft({
  output = "keyring:keyring",
  recipe = {
    { "",           "group:wire", ""           },
    { "group:wire", "group:key",  "group:wire" },
    { "",           "group:wire", ""           },
  },
  replacements = {
    { "group:wire", "basic_materials:empty_spool" },
    { "group:wire", "basic_materials:empty_spool" },
    { "group:wire", "basic_materials:empty_spool" },
    { "group:wire", "basic_materials:empty_spool" }
  },
})
``` and the line about replacement is desplayed 4 times on each wire, instead of 1 time on each wire.

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/craftguide/commit/1980fefa50a63e09f6793c840aeb1a87c03f6699

The repeating string **is not** a bug, the `replacements` field supports more than one entry.

**Comment by kilbith** [comment]
By the way, I can't seem to find an item with the `wire` group. I looked though the `basic_materials` and I can't see any declaration to the `wire` group.

**Comment by louisroyer** [comment]
> By the way, I can't seem to find an item with the `wire` group. I looked though the `basic_materials` and I can't see any declaration to the `wire` group.

Be sure to use the latest version of `basic_materials` (from today on master).

**Comment by kilbith** [comment]
`{ "group:wire", "basic_materials:empty_spool"}` would work too. Each wire slot will get replaced by `basic_materials:empty_spool`, respectively.

**Comment by kilbith** [comment]
You can return back to the previous declaration: https://github.com/minetest-mods/craftguide/commit/e6d1857799ea81bd

**Pull request closed without merging**
