### PR TITLE
Replace deprecated method 'setting_getbool' with 'settings:get_bool'

### PR DESCRIPTION
**Pull request by AntumDeluge**
May not want to merge this until after 0.4.16 release, as the new ['settings' object calls][l_settings] are not available in 0.4.15.

[l_settings]: https://github.com/minetest/minetest/blob/43d1f375d18a2fbc547a9b4f23d1354d645856ca/src/script/lua_api/l_settings.cpp#L267

### CODE REVIEW

**Comment by tacotexmex** [comment]
0.4.16 is here. Please merge.

**Comment by kilbith** [comment]
I'll wait until more servers switch over to 0.4.16.

**Comment by tacotexmex** [comment]
Okay. Just curious, how would you know when that is?

**Comment by AntumDeluge** [comment]
Why not create a new 'dev' or '0.4.16' branch & merge it to that?

**Comment by kilbith** [comment]
Actually, I don't actually need a pull-request for that. But thanks anyway.

**Pull request closed without merging**
